var kommune_daekning = [
    {"name": "UU Aarhus Samsø","kommuner":['aarhus.json','samsoe.json']},
    {"name": "UU Aalborg","kommuner":['aalborg.json']},
    {"name": "UU Aabenraa","kommuner":['aabenraa.json']},
    {"name": "UU Billund","kommuner":['billund.json']},
    {"name": "UU Bornholm","kommuner":['bornholm.json']},
    {"name": "UU Center Syd","kommuner": ['hvidovre.json','broendby.json','ishoej.json']},
    {"name": "UU Center Sydfyn","kommuner":['faaborg.json','langeland.json','svendborg.json','aeroe.json']},
    {"name": "UU Djursland","kommuner": ['norddjurs.json','syddjurs.json']},
    {"name": "UU Esbjerg","kommuner":['esbjerg.json','fanoe.json'] },
    {"name": "UU Favrskov","kommuner":['favrskov.json']},
    {"name": "UU Frederiksberg" ,"kommuner":['frederiksberg.json']},
    {"name": "UU Frederikshavn" ,"kommuner":['frederikshavn.json']},
    {"name": "UU Gribskov" ,"kommuner":['gribskov.json']},
    {"name": "UU Guldborgsund" ,"kommuner":['guldborgsund.json']},
    {"name": "UU Haderslev" ,"kommuner":['haderslev.json']},
    {"name": "UU Halsnæs/Hillerød","kommuner":['halsnaes.json','hilleroed.json']},
    {"name": "UU Hedensted" ,"kommuner":['hedensted.json']},
    {"name": "UU Herning" ,"kommuner":['herning.json']},
    {"name": "UU Horsens","kommuner": ['horsens.json']},
    {"name": "UU Hjørring","kommuner":['hjoerring.json']},
    {"name": "UU Ikast Brande" ,"kommuner":['ikast.json']},
    {"name": "UU Jammerbugt" ,"kommuner":['jammerbugt.json']},
    {"name": "UU Kolding" ,"kommuner":['kolding.json']},
    {"name": "UU København" ,"kommuner":['koebenhavn.json']},
    {"name": "UU Lillebælt" ,"kommuner":['fredericia.json','middelfart.json']},
    {"name": "UU Lolland" ,"kommuner":['lolland.json']},
    {"name": "UU Mariagerfjord" ,"kommuner":['mariagerfjord.json']},
    {"name": "UU Mors" ,"kommuner":['morsoe.json']},
    {"name": "UU Nord" ,"kommuner":['gladsaxe.json','lyngby.json','gentofte.json','herlev.json']},
    {"name": "UU Nordvestjylland","kommuner":['holstebro.json','struer.json','lemvig.json']},
    {"name": "UU Nordvestsjælland" ,"kommuner":['odsherred.json','kalundborg.json','holbaek.json']},
    {"name": "UU Odder Skanderborg" ,"kommuner":['odder.json','skanderborg.json']},
    {"name": "UU Odense og Omegn" ,"kommuner":['nordfyns.json','kerteminde.json','nyborg.json','odense.json','assens.json']},
    {"name": "UU Randers" ,"kommuner":['randers.json']},
    {"name": "UU Rebild" ,"kommuner":['rebild.json']},
    {"name": "UU Ringkøbing Skjern" ,"kommuner":['ringkobing.json']},
    {"name": "UU Roskilde Lejre" ,"kommuner":['roskilde.json','lejre.json']},
    {"name": "UU Silkeborg" ,"kommuner":['silkeborg.json']},
    {"name": "UU Sjælland Syd" ,"kommuner":['naestved.json','vordingborg.json','faxe.json']},
    {"name": "UU Sjælsø" ,"kommuner":['alleroed.json','furesoe.json','hoersholm.json','rudersdal.json']},
    {"name": "UU Skive" ,"kommuner":['skive.json']},
    {"name": "UU Sønderborg" ,"kommuner":['soenderborg.json']},
    {"name": "UU Thy" ,"kommuner":['thisted.json']},
    {"name": "UU Tønder" ,"kommuner":['toender.json']},
    {"name": "UU Tårnby" ,"kommuner":['taarnby.json','dragoe.json']},
   
];
  var kommune_daekningJson = [
    {"name": "UU Sjælland Syd" ,"kommuner":['naestved.json','kommuner.json','faxe.json']},
    {"name": "UU Aarhus Samsø","kommuner":['aarhus.json','samsoe.json']},
    {"name": "UU Aalborg","kommuner":['aalborg.json']},
    {"name": "UU Aabenraa","kommuner":['aabenraa.json']},
    {"name": "UU Billund","kommuner":['billund.json']},
    {"name": "UU Bornholm","kommuner":['bornholm.json']},
    {"name": "UU Center Syd","kommuner": ['hvidovre.json','broendby.json','ishoej.json']},
    {"name": "UU Center Sydfyn","kommuner":['faaborg.json','langeland.json','svendborg.json','aeroe.json']},
    {"name": "UU Djursland","kommuner": ['norddjurs.json','syddjurs.json']},
    {"name": "UU Esbjerg","kommuner":['esbjerg.json','fanoe.json'] },
    {"name": "UU Favrskov","kommuner":['favrskov.json']},
    {"name": "UU Frederiksberg" ,"kommuner":['frederiksberg.json']},
    {"name": "UU Frederikshavn" ,"kommuner":['frederikshavn.json']},
    {"name": "UU Gribskov" ,"kommuner":['gribskov.json']},
    {"name": "UU Haderslev" ,"kommuner":['haderslev.json']},
    {"name": "UU Halsnæs/Hillerød","kommuner":['halsnaes.json','hilleroed.json']},
    {"name": "UU Hedensted" ,"kommuner":['hedensted.json']},
    {"name": "UU Herning" ,"kommuner":['herning.json']},
    {"name": "UU Horsens","kommuner": ['horsens.json']},
    {"name": "UU Hjørring","kommuner":['hjoerring.json']},
    {"name": "UU Ikast Brande" ,"kommuner":['ikast.json']},
    {"name": "UU Jammerbugt" ,"kommuner":['jammerbugt.json']},
    {"name": "UU Kolding" ,"kommuner":['kolding.json']},
    {"name": "UU København" ,"kommuner":['koebenhavn.json']},
    {"name": "UU Lillebælt" ,"kommuner":['fredericia.json','middelfart.json']},
    {"name": "UU Lolland Falster" ,"kommuner":['lolland.json','guldborgsund.json']},
    {"name": "UU Mariagerfjord" ,"kommuner":['mariagerfjord.json']},
    {"name": "UU Mors" ,"kommuner":['morsoe.json']},
    {"name": "UU Nord" ,"kommuner":['gladsaxe.json','lyngby.json','gentofte.json','herlev.json']},
    {"name": "UU Nordvestjylland","kommuner":['holstebro.json','struer.json','lemvig.json']},
    {"name": "UU Nordvestsjælland" ,"kommuner":['odsherred.json','kalundborg.json','holbaek.json']},
    {"name": "UU Odder Skanderborg" ,"kommuner":['odder.json','skanderborg.json']},
    {"name": "UU Odense og Omegn" ,"kommuner":['nordfyns.json','kerteminde.json','nyborg.json','odense.json','assens.json']},
    {"name": "UU Randers" ,"kommuner":['randers.json']},
    {"name": "UU Rebild" ,"kommuner":['rebild.json']},
    {"name": "UU Ringkøbing Skjern" ,"kommuner":['ringkobing.json']},
    {"name": "UU Roskilde Lejre" ,"kommuner":['roskilde.json','lejre.json']},
    {"name": "UU Silkeborg" ,"kommuner":['silkeborg.json']},
    {"name": "UU Sjælsø" ,"kommuner":['alleroed.json','furesoe.json','hoersholm.json','rudersdal.json']},
    {"name": "UU Skive" ,"kommuner":['skive.json']},
    {"name": "UU Sønderborg" ,"kommuner":['soenderborg.json']},
    {"name": "UU Thy" ,"kommuner":['thisted.json']},
    {"name": "UU Tønder" ,"kommuner":['toender.json']},
    {"name": "UU Tårnby" ,"kommuner":['taarnby.json','dragoe.json']},
    {"name": "UU V Køge Bugt" ,"kommuner":['greve.json','koege.json','solroed.json','stevns.json']},
    {"name": "UU Varde","kommuner":['varde.json']},
    {"name": "UU Vejle Study Support Center","kommuner":['vejle.json']},
    {"name": "UU Brønderslev","kommuner":['broenderslev.json']},
    {"name": "UU Vallensbæk","kommuner":['vallensbaek.json']},
    {"name": "UU Vejen","kommuner":['vejen.json']},
    {"name": "UU Vest Region Hovedstaden","kommuner":['egedal.json','frederikssund.json']},
    {"name": "UU Vestegnen","kommuner":['albertslund.json','glostrup.json','ballerup.json','hoejetaastrup.json','roedovre.json']},
    {"name": "UU Vesthimmerland","kommuner":['vesthimmerlands.json']},
    {"name": "UU Vestsjælland","kommuner":['ringsted.json','soroe.json','slagelse.json']},
    {"name": "UU Viborg","kommuner":['viborg.json']},
    {"name": "UU Øresund","kommuner":['fredensborg.json','helsingoer.json']}
  ]
                                /*   
                       
        
               
               
                
                case  "UU Øresund":
                        res = ['fredensborg.json','helsingoer.json'];
                        break;
                
                
                
                */
              