var kommune_daekning = [
    {"name": "UU Aarhus Samsø","kommuner":['aarhus.kml','samsoe.kml']},
    {"name": "UU Aalborg","kommuner":['aalborg.kml']},
    {"name": "UU Aabenraa","kommuner":['aabenraa.kml']},
    {"name": "UU Billund","kommuner":['billund.kml']},
    {"name": "UU Bornholm","kommuner":['bornholm.kml']},
    {"name": "UU Center Syd","kommuner": ['hvidovre.kml','broendby.kml','ishoej.kml']},
    {"name": "UU Center Sydfyn","kommuner":['faaborg.kml','langeland.kml','svendborg.kml','aeroe.kml']},
    {"name": "UU Djursland","kommuner": ['norddjurs.kml','syddjurs.kml']},
    {"name": "UU Esbjerg","kommuner":['esbjerg.kml','fanoe.kml'] },
    {"name": "UU Favrskov","kommuner":['favrskov.kml']},
    {"name": "UU Frederiksberg" ,"kommuner":['frederiksberg.kml']},
    {"name": "UU Frederikshavn" ,"kommuner":['frederikshavn.kml']},
    {"name": "UU Gribskov" ,"kommuner":['gribskov.kml']},
    {"name": "UU Haderslev" ,"kommuner":['haderslev.kml']},
    {"name": "UU Halsnæs/Hillerød","kommuner":['halsnaes.kml','hilleroed.kml']},
    {"name": "UU Hedensted" ,"kommuner":['hedensted.kml']},
    {"name": "UU Herning" ,"kommuner":['herning.kml']},
    {"name": "UU Horsens","kommuner": ['horsens.kml']},
    {"name": "UU Hjørring","kommuner":['hjoerring.kml']},
    {"name": "UU Ikast Brande" ,"kommuner":['ikast.kml']},
    {"name": "UU Jammerbugt" ,"kommuner":['jammerbugt.kml']},
    {"name": "UU Kolding" ,"kommuner":['kolding.kml']},
    {"name": "UU København" ,"kommuner":['koebenhavn.kml']},
    {"name": "UU Lillebælt" ,"kommuner":['fredericia.kml','middelfart.kml']},
    {"name": "UU Lolland Falster" ,"kommuner":['lolland.kml','guldborgsund.kml']},
    {"name": "UU Mariagerfjord" ,"kommuner":['mariagerfjord.kml']},
    {"name": "UU Mors" ,"kommuner":['morsoe.kml']},
    {"name": "UU Nord" ,"kommuner":['gladsaxe.kml','lyngby.kml','gentofte.kml','herlev.kml']},
    {"name": "UU Nordvestjylland","kommuner":['holstebro.kml','struer.kml','lemvig.kml']},
    {"name": "UU Nordvestsjælland" ,"kommuner":['odsherred.kml','kalundborg.kml','holbaek.kml']},
    {"name": "UU Odder Skanderborg" ,"kommuner":['odder.kml','skanderborg.kml']},
    {"name": "UU Odense og Omegn" ,"kommuner":['nordfyns.kml','kerteminde.kml','nyborg.kml','odense.kml','assens.kml']},
    {"name": "UU Randers" ,"kommuner":['randers.kml']},
    {"name": "UU Rebild" ,"kommuner":['rebild.kml']},
    {"name": "UU Ringkøbing Skjern" ,"kommuner":['ringkobing.kml']},
    {"name": "UU Roskilde Lejre" ,"kommuner":['roskilde.kml','lejre.kml']},
    {"name": "UU Silkeborg" ,"kommuner":['silkeborg.kml']},
    {"name": "UU Sjælland Syd" ,"kommuner":['naestved.kml','vordingborg.kml','faxe.kml']},
    {"name": "UU Sjælsø" ,"kommuner":['alleroed.kml','furesoe.kml','hoersholm.kml','rudersdal.kml']},
    {"name": "UU Skive" ,"kommuner":['skive.kml']},
    {"name": "UU Sønderborg" ,"kommuner":['soenderborg.kml']},
    {"name": "UU Thy" ,"kommuner":['thisted.kml']},
    {"name": "UU Tønder" ,"kommuner":['toender.kml']},
    {"name": "UU Tårnby" ,"kommuner":['taarnby.kml','dragoe.kml']},
   
];